import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  javascript: [{ type: "autogenerated", dirName: "javascript/javascript" }],
  typescript: [{ type: "autogenerated", dirName: "javascript/typescript" }],
  nodejs: [{ type: "autogenerated", dirName: "javascript/nodejs" }],

  dart: [{ type: "autogenerated", dirName: "dart/dart" }],
  flutter: [{ type: "autogenerated", dirName: "dart/flutter" }],

  er_diagram: [{ type: "autogenerated", dirName: "sql/er_diagram" }],
  postgresql: [{ type: "autogenerated", dirName: "sql/postgresql" }],

  sql: [{ type: "autogenerated", dirName: "sql/sql" }],
};

export default sidebars;
